### ISSUE TITLE
Study kotlin Until chapter 1~3

### ISSUE THREAD

**Issue by Taehyuny** [Breaking-Dope/breaking-android#3]
- 1장 : 코틀린 시작하기
- 2장 : 변수와 자료형, 연산
- 3장 : 함수와 함수형 프로그래밍

Study URL : https://sungje365.tistory.com/22?category=576891 

issue 종료 조건 : 두 명 다 공부가 어느정도 완료되었다면 이슈 close

**Comment by SeungGun** [comment]
2022-06-24 11:37: 내용 자체는 이해 완료. 하지만 암기형식으로 각각의 규칙들을 전부 외우는 것은 비효율적이라 생각하므로
완료 처리 선언합니다.

**Comment by Taehyuny** [comment]
2022-6-24 11:38: 람다 표현식과 같은 부분에 대해 익숙해질 필요가 있음. 내용 전반에 대해 이해하였으며, 실제 코딩을 통해 더욱 구체적인 이해가 필요해보임.
